# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='serverip',
            field=models.GenericIPAddressField(),
        ),
    ]
