# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-11-03 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20171103_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='serverip',
            field=models.CharField(max_length=100),
        ),
    ]
