# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_server_latest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topoid', models.CharField(max_length=20)),
                ('topoinfo', models.TextField()),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
